version: '2'
services:
  mysql:
      image: 'mysql:5.7.21'
      volumes:
        - 'db_data:/MonicaHQ'
      environment:
        - MYSQL_ROOT_PASSWORD=${db_root_password}
        - MYSQL_USER=${db_user}
        - MYSQL_PASSWORD=${db_user_password}
        - MYSQL_DATABASE=${db_database_name}
  monica:
      image: 'monicahq/monicahq'
      volumes:
        - 'MonicaHQ_data:/MonicaHQ'
      links:
        - mysql
      environment:
        - DB_DATABASE=${db_database_name}
        - DB_USERNAME=${db_user}
        - DB_PASSWORD=${db_user_password}
        - DB_HOST=mysql
        - DB_PORT=3306
        - APP_ENV=${app_env}
        - APP_DEBUG=false
        - CACHE_DRIVER=database
        - SESSION_DRIVER=file
        - SESSION_LIFETIME=120
        - QUEUE_DRIVER=sync
        - APP_KEY=gjlvf0rqKM)AVZkGGHao&!0(6anutx%w
        - HASH_SALT=Ceakge2eey20+Keyr12g4h
        - HASH_LENGTH=18
        - APP_URL=$_SERVER['HTTP_HOST']
        - DB_USE_UTF8MB4=true
        - MAIL_DRIVER=smtp
        - MAIL_HOST=${MAIL_HOST}
        - MAIL_PORT=${MAIL_PORT}
        - MAIL_USERNAME=${MAIL_USERNAME}
        - MAIL_PASSWORD=${MAIL_PASSWORD}
        - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
        - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
        - MAIL_FROM_NAME=${MAIL_FROM_NAME}
        - APP_EMAIL_NEW_USERS_NOTIFICATION=${APP_EMAIL_NEW_USERS_NOTIFICATION}
        - APP_DEFAULT_LOCALE=en
        - APP_DISABLE_SIGNUP=${app_disable_signup}
        - APP_SIGNUP_DOUBLE_OPTIN=false
        - APP_TRUSTED_CLOUDFLARE=false
        - LOG_CHANNEL=daily
        - SENTRY_SUPPORT=false
        - SENTRY_LARAVEL_DSN=
        - CHECK_VERSION=true
        - DEFAULT_MAX_UPLOAD_SIZE=10240
        - DEFAULT_MAX_STORAGE_SIZE=1024
        - DEFAULT_FILESYSTEM=public
        - MFA_ENABLED=false
        - CARDDAV_ENABLED=false
        - ALLOW_STATISTICS_THROUGH_PUBLIC_API_ACCESS=false
        - POLICY_COMPLIANT=true
        - REQUIRES_SUBSCRIPTION=false
  monica-lb:
    image: rancher/lb-service-haproxy:v0.7.5
    ports:
      - ${public_port}:${public_port}
volumes:
  db_data:
    driver: ${volume_driver}
  MonicaHQ_data:
    driver: ${volume_driver}
