version: '2'
catalog:
  name: "PBX"
  version: "v0.1 Catalog"
  description: "PBX System"
  uuid: Heimdall-1
  minimum_rancher_version: v0.51.0
  questions:
    - variable: volume_driver
      description: "Volume driver to use with this service"
      label: "Volume driver"
      required: true
      default: "local"
      type: enum
      options:
        - local
        - rancher-nfs
        - rancher-efs
        - rancher-ebs
services:
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      interval: 2000
      port: 42
      unhealthy_threshold: 3
  3CX:
    scale: 1
    retain_ip: true
    health_check:
      port: 5001
      interval: 5000
      unhealthy_threshold: 3
      request_line: 'GET / HTTP/1.0'
      healthy_threshold: 2
      response_timeout: 5000
