version: '2'
services:
  heimdall:
      image: 'linuxserver/heimdall'
      volumes:
        - 'heimdall_data:/heimdall'
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/New_York
  bookstack-lb:
    image: rancher/lb-service-haproxy:v0.7.5
    ports:
      - ${public_port}:${public_port}
volumes:
  heimdall_data:
    driver: ${volume_driver}
