version: '2'
catalog:
  name: "Heimdall"
  version: "v0.1 Catalog"
  description: "Application dashboard"
  uuid: Heimdall-1
  minimum_rancher_version: v0.51.0
  questions:
    - variable: public_port
      description: "public port to access the WordPress site"
      label: "Public Port"
      required: true
      default: "80"
      type: "int"
    - variable: volume_driver
      description: "Volume driver to use with this service"
      label: "Volume driver"
      required: true
      default: "local"
      type: enum
      options:
        - local
        - rancher-nfs
        - rancher-efs
        - rancher-ebs
services:
  heimdall-lb:
    scale: 1
    lb_config:
      certs: []
      port_rules:
      - protocol: http
        service: heimdall
        source_port: ${public_port}
        target_port: 80
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      interval: 2000
      port: 42
      unhealthy_threshold: 3
  heimdall:
    scale: 1
    retain_ip: true
    health_check:
      port: 80
      interval: 5000
      unhealthy_threshold: 3
      request_line: 'GET / HTTP/1.0'
      healthy_threshold: 2
      response_timeout: 5000
