version: '2'
services:
  3CXPBX:
      image: 'farfui/3cx:15.5'
      volumes:
        - 3cx_backup:/mnt/backup
        - 3cx_recordings:/mnt/recordings
        - 3cx_log:/var/log
        - 3cx_sys:/sys/fs/cgroup:ro
      ports:
        - "5001:5001"
        - "5015:5015"
        - "5060:5060"
        - "5060:5060/udp"
        - "5061:5061"
        - "5061:5061/udp"
        - "5090:5090"
        - "5090:5090/udp"
        - "9000-10999:9000-10999/udp"
      cap_add:
        - SYS_ADMIN
volumes:
  3CX_backup:
    driver: ${volume_driver}
  3CX_recordings:
      driver: ${volume_driver}
  3CX_log:
        driver: ${volume_driver}
  3CX_sys:
        driver: ${volume_driver}
